spring:
  datasource:
    url: jdbc:h2:mem:credit_loan_system_db
    username: johnny
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
spring-doc:
  swagger-ui:
    path: /swagger-ui.html